version: '2'

services:
  mongo:
    container_name: mongo
    build: 
      context: ./mongo/
    volumes:
      - /data/db/:/data/db/
    ports:
      - "27017:27017"
    networks:
      beerNet:
        ipv4_address: 10.0.1.2
  
  # chat:
  #   container_name: chat
  #   build:
  #     context: ./chat/
  #   volumes:
  #     - ../chatApp/:/opt/chatApp/
  #   ports:
  #     - "8081:8081"
  #   networks:
  #     beerNet:
  #       ipv4_address: 10.0.1.3

networks:
  beerNet:
    driver: bridge
    ipam:
      config:
      - subnet: 10.0.1.0/24
