version: '2'

services:
  mongo:
    container_name: mongo
    build: 
      context: ./mongo/
    volumes:
      - /data/db/:/data/db/
    ports:
      - "27017:27017"
    networks:
      beerNet:
        ipv4_address: 10.0.1.2

  backend:
    container_name: backend
    build:
      context: ./backend/
    ports:
      - "8080:8080"
    networks:
      beerNet:
        ipv4_address: 10.0.1.3
    depends_on:
      - mongo

networks:
  beerNet:
    driver: bridge
    ipam:
      config:
      - subnet: 10.0.1.0/24
